//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientChessBoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameState
    {
        public int GameStateId { get; set; }
        public int GameId { get; set; }
        public string Board { get; set; }
        public bool ClientTurn { get; set; }
        public bool IsNewGame { get; set; }
        public bool IsClientTurn { get; set; }
        public bool IsChess { get; set; }
        public bool IsChessMat { get; set; }
    }
}
